In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2
import os

In [2]:
# имена папок. они же - имена классов.
labels=['karabin','hryvnia','stepler','trash']
#извлекаем списки файлов для каждой папки.
filelists={}
for i in labels:
    filelists[i]=os.listdir(i)

In [3]:
dataset=dict()
des_list=['orb','sift','brisk']
for i in des_list:
    dataset[i]=pd.read_csv(f"{i}_dataset.csv")

In [4]:
X_train=dict()
y_train=dict()
X_test=dict()
y_test=dict()

from sklearn.model_selection import train_test_split
for i in des_list:
    temp=dataset[i].drop(columns=['pathname'])
    X_train[i], X_test[i], \
    y_train[i], y_test[i]=train_test_split(temp.drop(columns=['target']),temp['target'], \
                                           test_size=0.2, random_state=0,stratify=temp['target'])

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import *
pred=dict()
from joblib import dump, load

for i in des_list:
    clf=LogisticRegression()
    clf.fit(X_train[i], y_train[i])
    from joblib import dump, load
    pred[i]=clf.predict(X_test[i])
    print(f"{i}:")
    print(clf.classes_)
    print(f"Common accuracy: {accuracy_score(y_test[i],pred[i])} "   )
    print(f"Confusion matrix: \n {confusion_matrix(y_test[i],pred[i])}")
    print(f"Multilabel-confusion matrix: \n {multilabel_confusion_matrix(y_test[i],pred[i])} " )
    print("\n")
    
    dump(clf, f'written_models/{i}_logreg.joblib') 

/home/ivan/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/ivan/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n

orb:
['hryvnia' 'karabin' 'stepler' 'trash']
Common accuracy: 0.5454545454545454 
Confusion matrix: 
 [[24  1  3  2]
 [ 2  8  4  6]
 [ 8  3 16  2]
 [10  0  4  6]]
Multilabel-confusion matrix: 
 [[[49 20]
  [ 6 24]]

 [[75  4]
  [12  8]]

 [[59 11]
  [13 16]]

 [[69 10]
  [14  6]]] 


sift:
['hryvnia' 'karabin' 'stepler' 'trash']
Common accuracy: 0.5454545454545454 
Confusion matrix: 
 [[23  3  0  4]
 [ 2 13  4  1]
 [11  2 13  3]
 [ 9  1  5  5]]
Multilabel-confusion matrix: 
 [[[47 22]
  [ 7 23]]

 [[73  6]
  [ 7 13]]

 [[61  9]
  [16 13]]

 [[71  8]
  [15  5]]] 


brisk:
['hryvnia' 'karabin' 'stepler' 'trash']
Common accuracy: 0.5510204081632653 
Confusion matrix: 
 [[21  0  5  3]
 [ 0 11  7  2]
 [ 7  5 17  0]
 [ 8  4  3  5]]
Multilabel-confusion matrix: 
 [[[54 15]
  [ 8 21]]

 [[69  9]
  [ 9 11]]

 [[54 15]
  [12 17]]

 [[73  5]
  [15  5]]] 




/home/ivan/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [6]:
from sklearn.svm import SVC
from sklearn.metrics import *
pred=dict()

for i in des_list:
    clf=SVC()
    clf.fit(X_train[i], y_train[i])
    pred[i]=clf.predict(X_test[i])
    print(f"{i}:")
    print(clf.classes_)
    print(f"Common accuracy: {accuracy_score(y_test[i],pred[i])} "   )
    print(f"Confusion matrix: \n {confusion_matrix(y_test[i],pred[i])}")
    print(f"Multilabel-confusion matrix: \n {multilabel_confusion_matrix(y_test[i],pred[i])} " )
    print("\n")
    
    dump(clf, f'written_models/{i}_svm.joblib')

orb:
['hryvnia' 'karabin' 'stepler' 'trash']
Common accuracy: 0.6767676767676768 
Confusion matrix: 
 [[28  0  1  1]
 [ 2 12  5  1]
 [ 4  4 20  1]
 [ 7  2  4  7]]
Multilabel-confusion matrix: 
 [[[56 13]
  [ 2 28]]

 [[73  6]
  [ 8 12]]

 [[60 10]
  [ 9 20]]

 [[76  3]
  [13  7]]] 


sift:
['hryvnia' 'karabin' 'stepler' 'trash']
Common accuracy: 0.6161616161616161 
Confusion matrix: 
 [[29  0  1  0]
 [ 7 11  2  0]
 [ 6  3 19  1]
 [12  0  6  2]]
Multilabel-confusion matrix: 
 [[[44 25]
  [ 1 29]]

 [[76  3]
  [ 9 11]]

 [[61  9]
  [10 19]]

 [[78  1]
  [18  2]]] 


brisk:
['hryvnia' 'karabin' 'stepler' 'trash']
Common accuracy: 0.6428571428571429 
Confusion matrix: 
 [[25  2  2  0]
 [ 1 12  6  1]
 [ 8  0 20  1]
 [ 9  1  4  6]]
Multilabel-confusion matrix: 
 [[[51 18]
  [ 4 25]]

 [[75  3]
  [ 8 12]]

 [[57 12]
  [ 9 20]]

 [[76  2]
  [14  6]]] 




In [7]:
#from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import *
pred=dict()

for i in des_list:
    clf=RandomForestClassifier(n_estimators=200)
    clf.fit(X_train[i], y_train[i])
    pred[i]=clf.predict(X_test[i])
    print(f"{i}:")
    print(clf.classes_)
    print(f"Common accuracy: {accuracy_score(y_test[i],pred[i])} "   )
    print(f"Confusion matrix: \n {confusion_matrix(y_test[i],pred[i])}")
    print(f"Multilabel-confusion matrix: \n {multilabel_confusion_matrix(y_test[i],pred[i])} " )
    print("\n")
    
    dump(clf, f'written_models/{i}_randomforest.joblib')

orb:
['hryvnia' 'karabin' 'stepler' 'trash']
Common accuracy: 0.5757575757575758 
Confusion matrix: 
 [[27  0  3  0]
 [ 3  9  7  1]
 [ 8  3 17  1]
 [10  1  5  4]]
Multilabel-confusion matrix: 
 [[[48 21]
  [ 3 27]]

 [[75  4]
  [11  9]]

 [[55 15]
  [12 17]]

 [[77  2]
  [16  4]]] 


sift:
['hryvnia' 'karabin' 'stepler' 'trash']
Common accuracy: 0.6767676767676768 
Confusion matrix: 
 [[27  0  3  0]
 [ 4 13  2  1]
 [ 4  5 20  0]
 [ 6  2  5  7]]
Multilabel-confusion matrix: 
 [[[55 14]
  [ 3 27]]

 [[72  7]
  [ 7 13]]

 [[60 10]
  [ 9 20]]

 [[78  1]
  [13  7]]] 


brisk:
['hryvnia' 'karabin' 'stepler' 'trash']
Common accuracy: 0.6020408163265306 
Confusion matrix: 
 [[24  3  2  0]
 [ 2  9  8  1]
 [ 8  0 21  0]
 [ 9  2  4  5]]
Multilabel-confusion matrix: 
 [[[50 19]
  [ 5 24]]

 [[73  5]
  [11  9]]

 [[55 14]
  [ 8 21]]

 [[77  1]
  [15  5]]] 


