In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2
import os

In [2]:
# имена папок. они же - имена классов.
labels=['karabin','hryvnia','stepler','trash']
#извлекаем списки файлов для каждой папки.
filelists={}
for i in labels:
    filelists[i]=os.listdir(i)

In [3]:
dataset=dict()
des_list=['orb','sift','brisk']
for i in des_list:
    dataset[i]=pd.read_csv(f"{i}_dataset.csv")

In [4]:
X_train=dict()
y_train=dict()
X_test=dict()
y_test=dict()

from sklearn.model_selection import train_test_split
for i in des_list:
    temp=dataset[i].drop(columns=['pathname'])
    X_train[i], X_test[i], \
    y_train[i], y_test[i]=train_test_split(temp.drop(columns=['target']),temp['target'], \
                                           test_size=0.1, random_state=0,stratify=temp['target'])

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import *
pred=dict()
from joblib import dump, load

for i in des_list:
    clf=LogisticRegression(solver='newton-cg',C=0.01)
    clf.fit(X_train[i], y_train[i])
    from joblib import dump, load
    pred[i]=clf.predict(X_test[i])
    print(f"{i}:")
    print(clf.classes_)
    print(f"Common accuracy: {np.round( accuracy_score(y_test[i],pred[i]), 5)} "   )
    print(f"Precision:{np.round( precision_score(y_test[i],pred[i],average=None) , 5) }")
    print(f"Recall:{np.round( recall_score(y_test[i],pred[i],average=None), 5) }" )
    print(f"Confusion matrix:\n{confusion_matrix(y_test[i],pred[i])}")
    print("\n")
    
    dump(clf, f'written_models/{i}_logreg.joblib') 

orb:
['hryvnia' 'karabin' 'stepler' 'trash']
Common accuracy: 0.59615 
Precision:[0.56    0.83333 0.69231 0.375  ]
Recall:[0.93333 0.41667 0.6     0.3    ]
Confusion matrix:
[[14  0  1  0]
 [ 3  5  1  3]
 [ 3  1  9  2]
 [ 5  0  2  3]]


sift:
['hryvnia' 'karabin' 'stepler' 'trash']
Common accuracy: 0.61538 
Precision:[0.59091 0.85714 0.66667 0.45455]
Recall:[0.86667 0.5     0.53333 0.5    ]
Confusion matrix:
[[13  0  0  2]
 [ 1  6  3  2]
 [ 4  1  8  2]
 [ 4  0  1  5]]


brisk:
['hryvnia' 'karabin' 'stepler' 'trash']
Common accuracy: 0.62745 
Precision:[0.56    0.61538 0.875   0.6    ]
Recall:[0.93333 0.66667 0.5     0.3    ]
Confusion matrix:
[[14  1  0  0]
 [ 3  8  1  0]
 [ 2  3  7  2]
 [ 6  1  0  3]]




In [6]:
from sklearn.svm import SVC,LinearSVC
from sklearn.metrics import *
pred=dict()

for i in des_list:
    clf=SVC(C=100)
    clf.fit(X_train[i], y_train[i])
    pred[i]=clf.predict(X_test[i])
    print(f"{i}:")
    print(clf.classes_)
    print(f"Common accuracy: {np.round( accuracy_score(y_test[i],pred[i]), 5) } "   )
    print(f"Precision:{np.round( precision_score(y_test[i],pred[i],average=None), 5) }")
    print(f"Recall:{np.round(recall_score(y_test[i],pred[i],average=None),5) }" )
    print(f"Confusion matrix:\n{confusion_matrix(y_test[i],pred[i])}")
    print("\n")
    
    dump(clf, f'written_models/{i}_svm.joblib')

orb:
['hryvnia' 'karabin' 'stepler' 'trash']
Common accuracy: 0.63462 
Precision:[0.68421 0.6     0.6     0.625  ]
Recall:[0.86667 0.5     0.6     0.5    ]
Confusion matrix:
[[13  0  1  1]
 [ 2  6  2  2]
 [ 2  4  9  0]
 [ 2  0  3  5]]


sift:
['hryvnia' 'karabin' 'stepler' 'trash']
Common accuracy: 0.65385 
Precision:[0.61905 0.7     0.83333 0.44444]
Recall:[0.86667 0.58333 0.66667 0.4    ]
Confusion matrix:
[[13  1  0  1]
 [ 2  7  0  3]
 [ 4  0 10  1]
 [ 2  2  2  4]]


brisk:
['hryvnia' 'karabin' 'stepler' 'trash']
Common accuracy: 0.70588 
Precision:[0.66667 0.66667 0.81818 0.75   ]
Recall:[0.93333 0.83333 0.64286 0.3    ]
Confusion matrix:
[[14  0  1  0]
 [ 1 10  0  1]
 [ 2  3  9  0]
 [ 4  2  1  3]]




In [7]:
#from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import *
pred=dict()

for i in des_list:
    clf=RandomForestClassifier(n_estimators=200)
    clf.fit(X_train[i], y_train[i])
    pred[i]=clf.predict(X_test[i])
    print(f"{i}:")
    print(clf.classes_)
    print(f"Common accuracy: {np.round( accuracy_score(y_test[i],pred[i]),5)} "   )
    print(f"Precision:{np.round(precision_score(y_test[i],pred[i],average=None),5)}")
    print(f"Recall:{np.round(recall_score(y_test[i],pred[i],average=None),5)}" )
    print(f"Confusion matrix:\n{confusion_matrix(y_test[i],pred[i])}")
    print("\n")
    
    dump(clf, f'written_models/{i}_randomforest.joblib')

orb:
['hryvnia' 'karabin' 'stepler' 'trash']
Common accuracy: 0.59615 
Precision:[0.57692 0.83333 0.5625  0.5    ]
Recall:[1.      0.41667 0.6     0.2    ]
Confusion matrix:
[[15  0  0  0]
 [ 2  5  4  1]
 [ 4  1  9  1]
 [ 5  0  3  2]]


sift:
['hryvnia' 'karabin' 'stepler' 'trash']
Common accuracy: 0.65385 
Precision:[0.55556 0.69231 0.78571 0.57143]
Recall:[0.66667 0.75    0.73333 0.4    ]
Confusion matrix:
[[10  1  1  3]
 [ 3  9  0  0]
 [ 2  2 11  0]
 [ 3  1  2  4]]


brisk:
['hryvnia' 'karabin' 'stepler' 'trash']
Common accuracy: 0.62745 
Precision:[0.63158 0.63636 0.625   0.6    ]
Recall:[0.8     0.58333 0.71429 0.3    ]
Confusion matrix:
[[12  1  1  1]
 [ 0  7  4  1]
 [ 3  1 10  0]
 [ 4  2  1  3]]




In [13]:
#from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import *
pred=dict()

for i in des_list:
    clf=KNeighborsClassifier(n_neighbors=5, weights='distance')
    clf.fit(X_train[i], y_train[i])
    pred[i]=clf.predict(X_test[i])
    print(f"{i}:")
    print(clf.classes_)
    print(f"Common accuracy: {np.round( accuracy_score(y_test[i],pred[i]),5)} "   )
    print(f"Precision:{np.round(precision_score(y_test[i],pred[i],average=None),5)}")
    print(f"Recall:{np.round(recall_score(y_test[i],pred[i],average=None),5)}" )
    print(f"Confusion matrix:\n{confusion_matrix(y_test[i],pred[i])}")
    print("\n")
    
    dump(clf, f'written_models/{i}_knn.joblib')

orb:
['hryvnia' 'karabin' 'stepler' 'trash']
Common accuracy: 0.59615 
Precision:[0.625   0.6     0.54545 0.57143]
Recall:[1.  0.5 0.4 0.4]
Confusion matrix:
[[15  0  0  0]
 [ 2  6  3  1]
 [ 3  4  6  2]
 [ 4  0  2  4]]


sift:
['hryvnia' 'karabin' 'stepler' 'trash']
Common accuracy: 0.65385 
Precision:[0.56    0.66667 0.76923 0.8    ]
Recall:[0.93333 0.5     0.66667 0.4    ]
Confusion matrix:
[[14  1  0  0]
 [ 3  6  2  1]
 [ 3  2 10  0]
 [ 5  0  1  4]]


brisk:
['hryvnia' 'karabin' 'stepler' 'trash']
Common accuracy: 0.60784 
Precision:[0.52174 1.      0.6     0.5    ]
Recall:[0.8     0.58333 0.64286 0.3    ]
Confusion matrix:
[[12  0  2  1]
 [ 2  7  2  1]
 [ 4  0  9  1]
 [ 5  0  2  3]]


